// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBot.Infrastructure.Contexts;

#nullable disable

namespace SmartBot.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250623203526_SelectedUserId")]
    partial class SelectedUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("SmartBot.Abstractions.Models.Exporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastExportedReportId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastExportingDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastExportedReportId");

                    b.ToTable("Exporter", (string)null);
                });

            modelBuilder.Entity("SmartBot.Abstractions.Models.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EveningReportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MorningReportId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EveningReportId")
                        .IsUnique();

                    b.HasIndex("MorningReportId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("SmartBot.Abstractions.Models.Reports.UserReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApprovedBySystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Overdue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReportElements", (string)null);
                });

            modelBuilder.Entity("SmartBot.Abstractions.Models.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentReport")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<long?>("SelectedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SelectedWorkingChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WorkingChatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelectedUserId");

                    b.HasIndex("SelectedWorkingChatId");

                    b.HasIndex("WorkingChatId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartBot.Abstractions.Models.WorkingChats.WorkingChat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MessageThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkingChats", (string)null);
                });

            modelBuilder.Entity("SmartBot.Abstractions.Models.Exporter", b =>
                {
                    b.HasOne("SmartBot.Abstractions.Models.Reports.Report", null)
                        .WithMany()
                        .HasForeignKey("LastExportedReportId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SmartBot.Abstractions.Models.Reports.Report", b =>
                {
                    b.HasOne("SmartBot.Abstractions.Models.Reports.UserReport", "EveningReport")
                        .WithOne()
                        .HasForeignKey("SmartBot.Abstractions.Models.Reports.Report", "EveningReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartBot.Abstractions.Models.Reports.UserReport", "MorningReport")
                        .WithOne()
                        .HasForeignKey("SmartBot.Abstractions.Models.Reports.Report", "MorningReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBot.Abstractions.Models.Users.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EveningReport");

                    b.Navigation("MorningReport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBot.Abstractions.Models.Users.User", b =>
                {
                    b.HasOne("SmartBot.Abstractions.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SelectedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBot.Abstractions.Models.WorkingChats.WorkingChat", null)
                        .WithMany()
                        .HasForeignKey("SelectedWorkingChatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartBot.Abstractions.Models.WorkingChats.WorkingChat", "WorkingChat")
                        .WithMany()
                        .HasForeignKey("WorkingChatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("SmartBot.Abstractions.Models.Users.AnswerFor", "AnswerFor", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("EveningReport")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ReportId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("ToUserId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserId");

                            b1.HasIndex("ReportId");

                            b1.HasIndex("ToUserId");

                            b1.ToTable("AnswersFor", (string)null);

                            b1.HasOne("SmartBot.Abstractions.Models.Reports.Report", null)
                                .WithMany()
                                .HasForeignKey("ReportId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("SmartBot.Abstractions.Models.Users.User", null)
                                .WithMany()
                                .HasForeignKey("ToUserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("SmartBot.Abstractions.Models.Users.ReviewingReport", "ReviewingReport", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("EveningReport")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ReportId")
                                .HasColumnType("TEXT");

                            b1.HasKey("UserId");

                            b1.HasIndex("ReportId");

                            b1.ToTable("ReviewingReports", (string)null);

                            b1.HasOne("SmartBot.Abstractions.Models.Reports.Report", null)
                                .WithMany()
                                .HasForeignKey("ReportId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("AnswerFor");

                    b.Navigation("ReviewingReport");

                    b.Navigation("WorkingChat");
                });

            modelBuilder.Entity("SmartBot.Abstractions.Models.Users.User", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
